### ISSUE TITLE
レビュー感想 [こす]

### ISSUE THREAD

**Issue by kosu27** [sumiren/whoiam#29]
[感想]
全体的に綺麗にまとまっていて、とても見やすかったです👍
自分はApolloで実装したので、sumirenさんの実装方法はとても学びになりました。
testも実装されていたので、参考にさせていただきます🙇‍♂️

[レビュー]
気になったところ
・Twitterとgithub配下にあるボタンが少しずれていたので、統一できると綺麗になるかと思われます。
・GitHubの言語の表示がGitHubと異なっていました
e2e-testee (https://github.com/sumiren/e2e-testee)の表示が
github上では
JavaScript77.6%　Vue14.2%　TypeScript7.3%　HTML0.9%
実装上では
JavaScript77%　Vue16%　TypeScript7%になっていました。

細かいところばかりしか指摘できず申し訳ありません。
確認お願い致します🙇‍♂️

**Comment by sumiren** [comment]
@kosu27 

ありがとうございます！！

> GitHubの言語の表示がGitHubと異なっていました

これ、バグだったので修正しました！
